blank_issues_enabled: true

contact_links:
  - name: ä½¿ç”¨é—®é¢˜ ğŸ—¨ï¸
    url: https://github.com/dotnetcore/FreeSql/discussions
    about: ä½¿ç”¨è¿‡ç¨‹ä¸­çš„ç–‘é—®è¯·å‘å¸ƒåˆ°è¿™é‡Œ
  - name: æ–‡æ¡£é”™è¯¯ ğŸ“š
    url: https://github.com/2881099/FreeSql.Wiki.VuePress/issues/new
    about: å…³äºæ–‡æ¡£ç›¸å…³çš„é”™è¯¯è¯·æäº¤åˆ°è¿™é‡Œ
